version: '3.8'

services:
  app1:
    image: myapp:1
    command: bash -c 'uvicorn app.main:app --host 0.0.0.0 --port 8000'
    ports:
      - 8001:8000
  app2:
    image: myapp:2
    command: bash -c 'uvicorn app.main:app --host 0.0.0.0 --port 8000'
    ports:
      - 8002:8000